# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(255, 371)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.Circle = QtWidgets.QWidget()
        self.Circle.setObjectName("Circle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Circle)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_xcenter_circle = QtWidgets.QLabel(self.Circle)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_xcenter_circle.setFont(font)
        self.label_xcenter_circle.setObjectName("label_xcenter_circle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_xcenter_circle)
        self.spin_box_xcenter_circle = QtWidgets.QSpinBox(self.Circle)
        self.spin_box_xcenter_circle.setMaximum(1000)
        self.spin_box_xcenter_circle.setObjectName("spin_box_xcenter_circle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_box_xcenter_circle)
        self.label_ycenter_circle = QtWidgets.QLabel(self.Circle)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ycenter_circle.setFont(font)
        self.label_ycenter_circle.setObjectName("label_ycenter_circle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_ycenter_circle)
        self.spin_box_ycenter_circle = QtWidgets.QSpinBox(self.Circle)
        self.spin_box_ycenter_circle.setObjectName("spin_box_ycenter_circle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_box_ycenter_circle)
        spacerItem = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_circle_start_radius = QtWidgets.QLabel(self.Circle)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_circle_start_radius.setFont(font)
        self.label_circle_start_radius.setObjectName("label_circle_start_radius")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_circle_start_radius)
        self.spin_box_circle_radius = QtWidgets.QSpinBox(self.Circle)
        self.spin_box_circle_radius.setObjectName("spin_box_circle_radius")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_box_circle_radius)
        self.combobox_alg_circle = QtWidgets.QComboBox(self.Circle)
        self.combobox_alg_circle.setObjectName("combobox_alg_circle")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.combobox_alg_circle)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.widget_circle_color = QtWidgets.QWidget(self.Circle)
        self.widget_circle_color.setMinimumSize(QtCore.QSize(20, 20))
        self.widget_circle_color.setStyleSheet("background-color: black")
        self.widget_circle_color.setObjectName("widget_circle_color")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.widget_circle_color)
        self.button_circle_color = QtWidgets.QPushButton(self.Circle)
        self.button_circle_color.setObjectName("button_circle_color")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.button_circle_color)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(13, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.showCircleButton = QtWidgets.QPushButton(self.Circle)
        self.showCircleButton.setObjectName("showCircleButton")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.showCircleButton)
        self.label_circle_step = QtWidgets.QLabel(self.Circle)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_circle_step.setFont(font)
        self.label_circle_step.setObjectName("label_circle_step")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_circle_step)
        self.spinBox_circle_step = QtWidgets.QSpinBox(self.Circle)
        self.spinBox_circle_step.setObjectName("spinBox_circle_step")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBox_circle_step)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.label_circle_alg = QtWidgets.QLabel(self.Circle)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_circle_alg.setFont(font)
        self.label_circle_alg.setObjectName("label_circle_alg")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_circle_alg)
        self.button_circle_bg_color = QtWidgets.QPushButton(self.Circle)
        self.button_circle_bg_color.setObjectName("button_circle_bg_color")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.button_circle_bg_color)
        self.widget_circle_bg_color = QtWidgets.QWidget(self.Circle)
        self.widget_circle_bg_color.setMinimumSize(QtCore.QSize(20, 20))
        self.widget_circle_bg_color.setMaximumSize(QtCore.QSize(20, 20))
        self.widget_circle_bg_color.setStyleSheet("background-color: white")
        self.widget_circle_bg_color.setObjectName("widget_circle_bg_color")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.widget_circle_bg_color)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(11, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.spinBox_circle_number = QtWidgets.QSpinBox(self.Circle)
        self.spinBox_circle_number.setObjectName("spinBox_circle_number")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_circle_number)
        self.label_circle_number = QtWidgets.QLabel(self.Circle)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_circle_number.setFont(font)
        self.label_circle_number.setObjectName("label_circle_number")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_circle_number)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.tabWidget.addTab(self.Circle, "")
        self.Ellipse = QtWidgets.QWidget()
        self.Ellipse.setObjectName("Ellipse")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Ellipse)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(11, 11, 11, 11)
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_ellipse_xc = QtWidgets.QLabel(self.Ellipse)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ellipse_xc.setFont(font)
        self.label_ellipse_xc.setObjectName("label_ellipse_xc")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ellipse_xc)
        self.spinBox_ellipse_xc = QtWidgets.QSpinBox(self.Ellipse)
        self.spinBox_ellipse_xc.setObjectName("spinBox_ellipse_xc")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_ellipse_xc)
        self.label_ellipse_yc = QtWidgets.QLabel(self.Ellipse)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ellipse_yc.setFont(font)
        self.label_ellipse_yc.setObjectName("label_ellipse_yc")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_ellipse_yc)
        self.spinBox_ellipse_yc = QtWidgets.QSpinBox(self.Ellipse)
        self.spinBox_ellipse_yc.setObjectName("spinBox_ellipse_yc")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_ellipse_yc)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        self.label_start_semiaxis_x = QtWidgets.QLabel(self.Ellipse)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_start_semiaxis_x.setFont(font)
        self.label_start_semiaxis_x.setObjectName("label_start_semiaxis_x")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_start_semiaxis_x)
        self.spinBox_start_semiaxis_x = QtWidgets.QSpinBox(self.Ellipse)
        self.spinBox_start_semiaxis_x.setObjectName("spinBox_start_semiaxis_x")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_start_semiaxis_x)
        self.label_start_semiaxis_y = QtWidgets.QLabel(self.Ellipse)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_start_semiaxis_y.setFont(font)
        self.label_start_semiaxis_y.setObjectName("label_start_semiaxis_y")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_start_semiaxis_y)
        self.spinBox_start_semiaxis_y = QtWidgets.QSpinBox(self.Ellipse)
        self.spinBox_start_semiaxis_y.setObjectName("spinBox_start_semiaxis_y")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_start_semiaxis_y)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        self.label_ellipse_number = QtWidgets.QLabel(self.Ellipse)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ellipse_number.setFont(font)
        self.label_ellipse_number.setObjectName("label_ellipse_number")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_ellipse_number)
        self.spinBox_ellipse_number = QtWidgets.QSpinBox(self.Ellipse)
        self.spinBox_ellipse_number.setObjectName("spinBox_ellipse_number")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBox_ellipse_number)
        self.label_ellipse_step_x = QtWidgets.QLabel(self.Ellipse)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ellipse_step_x.setFont(font)
        self.label_ellipse_step_x.setObjectName("label_ellipse_step_x")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_ellipse_step_x)
        self.spin_box_ellipse_step_x = QtWidgets.QSpinBox(self.Ellipse)
        self.spin_box_ellipse_step_x.setObjectName("spin_box_ellipse_step_x")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spin_box_ellipse_step_x)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem8)
        self.label_alg_ellipse = QtWidgets.QLabel(self.Ellipse)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_alg_ellipse.setFont(font)
        self.label_alg_ellipse.setObjectName("label_alg_ellipse")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_alg_ellipse)
        self.comboBox_ellipse_alg = QtWidgets.QComboBox(self.Ellipse)
        self.comboBox_ellipse_alg.setObjectName("comboBox_ellipse_alg")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.comboBox_ellipse_alg)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(11, QtWidgets.QFormLayout.FieldRole, spacerItem9)
        self.widget_ellipse_color = QtWidgets.QWidget(self.Ellipse)
        self.widget_ellipse_color.setMinimumSize(QtCore.QSize(20, 20))
        self.widget_ellipse_color.setStyleSheet("background-color: black")
        self.widget_ellipse_color.setObjectName("widget_ellipse_color")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.widget_ellipse_color)
        self.button_chose_ellipse_color = QtWidgets.QPushButton(self.Ellipse)
        self.button_chose_ellipse_color.setObjectName("button_chose_ellipse_color")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.button_chose_ellipse_color)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(13, QtWidgets.QFormLayout.FieldRole, spacerItem10)
        self.widget_ellipse_bg_color = QtWidgets.QWidget(self.Ellipse)
        self.widget_ellipse_bg_color.setMinimumSize(QtCore.QSize(20, 20))
        self.widget_ellipse_bg_color.setMaximumSize(QtCore.QSize(20, 20))
        self.widget_ellipse_bg_color.setStyleSheet("background-color: white")
        self.widget_ellipse_bg_color.setObjectName("widget_ellipse_bg_color")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.widget_ellipse_bg_color)
        self.button_ellipse_bg_color = QtWidgets.QPushButton(self.Ellipse)
        self.button_ellipse_bg_color.setObjectName("button_ellipse_bg_color")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.button_ellipse_bg_color)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(15, QtWidgets.QFormLayout.FieldRole, spacerItem11)
        self.button_draw_ellipse_spec = QtWidgets.QPushButton(self.Ellipse)
        self.button_draw_ellipse_spec.setObjectName("button_draw_ellipse_spec")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.button_draw_ellipse_spec)
        self.spinBox_ellipse_step_y = QtWidgets.QSpinBox(self.Ellipse)
        self.spinBox_ellipse_step_y.setObjectName("spinBox_ellipse_step_y")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBox_ellipse_step_y)
        self.label_ellipse_step_y = QtWidgets.QLabel(self.Ellipse)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ellipse_step_y.setFont(font)
        self.label_ellipse_step_y.setObjectName("label_ellipse_step_y")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_ellipse_step_y)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.tabWidget.addTab(self.Ellipse, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 255, 13))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_xcenter_circle.setText(_translate("MainWindow", "Xc"))
        self.label_ycenter_circle.setText(_translate("MainWindow", "Yc"))
        self.label_circle_start_radius.setText(_translate("MainWindow", "Start radius"))
        self.button_circle_color.setText(_translate("MainWindow", "Circle color"))
        self.showCircleButton.setText(_translate("MainWindow", "Show"))
        self.label_circle_step.setText(_translate("MainWindow", "Step"))
        self.label_circle_alg.setText(_translate("MainWindow", "Algorithm"))
        self.button_circle_bg_color.setText(_translate("MainWindow", "Background color"))
        self.label_circle_number.setText(_translate("MainWindow", "Quantity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Circle), _translate("MainWindow", "Circle"))
        self.label_ellipse_xc.setText(_translate("MainWindow", "Xc"))
        self.label_ellipse_yc.setText(_translate("MainWindow", "Yc"))
        self.label_start_semiaxis_x.setText(_translate("MainWindow", "Start semiaxis X"))
        self.label_start_semiaxis_y.setText(_translate("MainWindow", "Start semiaxis Y"))
        self.label_ellipse_number.setText(_translate("MainWindow", "Quantity"))
        self.label_ellipse_step_x.setText(_translate("MainWindow", "Step X"))
        self.label_alg_ellipse.setText(_translate("MainWindow", "Algorithm"))
        self.button_chose_ellipse_color.setText(_translate("MainWindow", "Ellipse color"))
        self.button_ellipse_bg_color.setText(_translate("MainWindow", "Background color"))
        self.button_draw_ellipse_spec.setText(_translate("MainWindow", "Show"))
        self.label_ellipse_step_y.setText(_translate("MainWindow", "Step Y"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Ellipse), _translate("MainWindow", "Ellipse"))

